### ISSUE TITLE
It seems to lack utils.py in this respository.

### ISSUE THREAD

**Issue by ODVV** [mingyr/san#1]
It seems to lack utils.py in this respository. 
Error here:
`from utils import Summaries`

**Comment by mingyr** [comment]
thanks for interesting in it.
it depends on another repo dnn-lib. i already push some code there. 
https://github.com/mingyr/dnn-lib

however if you are using TensorFlow 2.0, you might need to adjust it due to Sonnet undergoes a huge upgrade recently.

**Comment by ODVV** [comment]
thanks, it works now. I found your work is very interesting.
